### ISSUE TITLE
Add TypeScript declaration

### ISSUE THREAD

**Issue by muescha** [vfile/to-vfile#14]
### Subject of the feature

Add TypeScript declaration

### Alternatives

*source https://github.com/problem233/kosoite/blob/master/src/decl.d.ts#L57-L73*

```typescript
declare module 'to-vfile' {
  import { VFile as OrigVFile, VFileContents, VFileOptions } from 'vfile'
  import { WriteFileOptions } from 'fs'
  namespace toVFile {
    type VFile_ = Pick<OrigVFile, keyof OrigVFile>
    interface VFile extends VFile_ {} // to avoid expanding
    interface ToVFile {
      (input: VFileContents | VFile | VFileOptions): VFile
      <F extends Pick<VFile, keyof VFile>>(input: F): F
      read(input: VFileContents | VFile | VFileOptions, encoding?: string): Promise<VFile>
      read<F extends Pick<VFile, keyof VFile>>(input: F, encoding?: string): Promise<F>
      write(input: VFileContents | VFile | VFileOptions, fsOptions?: WriteFileOptions): Promise<void>
    }
  }
  const toVFile: toVFile.ToVFile
  export = toVFile
}
```

**Comment by ChristianMurphy** [comment]
There has been some discussion about this at
https://spectrum.chat/unified/general/rewriting-in-typescript~a420b99c-b416-457e-adbd-6f4dbdddf606
and https://spectrum.chat/unified/general/keeping-typescript-definitions-in-respective-repos~e3f49750-acb6-4075-8cbf-4daf072a2286

The current preference is to add typescript definitions to the repository.
We've been going repo by repo adding typings, there are over 300 repos in the unified ecosystem, this is one repo we haven't gotten to yet.
Feel free to open PRs to help move the migrations toward typings forward.

PRs are welcome!

**Comment by wooorm** [comment]
Going to close this, as I don’t think there’s a need for an issue in *every* repo, or in *some* repos: every unified repo w/o types accepts a PR to add them!
