### ISSUE TITLE
Add support for WHATWG URLs

### ISSUE THREAD

**Issue by aduh95** [vfile/to-vfile#16]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Subject

Node.js fs API supports URL for all fs operations, it'd be nice to add support for it

### Problem

I'd expect the following to work:

```js
import { toVFile } from 'to-vfile';
const doc = new URL('../hello.md', import.meta.url);
toVFile.readSync(doc, 'utf8');
```

Unfortunately, it's neither a string nor a buffer, no error is reported that I've done something forbidden but the VFile instance does not populate correctly.

### Solution

to-vfile could check if the provided object is a `URL` object, and convert it to a path using `fileURLToPath` from `node:url` module.

### Alternatives

to-vfile could throw an error if the provided object is a `URL` object, to let the user know they need to convert it themself:

```js
import { fileURLToPath } from 'url';
import { toVFile } from 'to-vfile';
const doc = new URL('../hello.md', import.meta.url);
toVFile.readSync(fileURLToPath(doc), 'utf8');
```

**Comment by wooorm** [comment]
heyy!

I was recently thinking of the same thing, as I’m in the process of moving everything over.
Probably also to `vfile`, and maybe other places.

The error would be a quick fix. Supporting them would be nicer (although: `vfile` is often used in the browser, so not using `url` would be preferred, but this doesn’t concern `to-vfile`).
Last, and maybe more for the future, would be to use URLs internally too, and changing the methods currently on `vfile` to be URL-centric.

**Comment by wooorm** [comment]
Here’s the code for `fileURLToPath`:

https://github.com/nodejs/node/blob/7ce9592cc0db4d131c66773188aef713ad977ca7/lib/internal/url.js#L1366

That seems fine.

**Comment by wooorm** [comment]
@aduh95 Is this something you could work on?

**Comment by wooorm** [comment]
Released!
