### ISSUE TITLE
`unified().process(toVFile.readSync)` doesn't work in v7 like it used to in v6

### ISSUE THREAD

**Issue by zigomir** [vfile/to-vfile#18]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: 7.1.0

I'm running a simple element filter over html file. Because I first read [this guide](https://unifiedjs.com/learn/guide/using-unified/#reporting) I started using `to-vfile` in order to read file from the disk. Because `v7` breaks this I started using native node's `readFileSync` on my project.

I still wanted to report this issue, if someone has same problem. It also looks like https://github.com/vfile/to-vfile/issues/15 reported same/similar thing.

### Steps to reproduce

1. clone the repo linked below
2. `cd v6 && yarn && node cleanup.mjs` and you'll see that `script` tag has been stripped out of the `index.html` contents
3. if you try same thing for v7 (cd back to root and run `cd v7 && yarn && node cleanup.mjs`) you'll see `script` tag is still in there

Link to code example: https://github.com/zigomir/to-vfile-v7-reproduction

### Expected behavior

I believe it should work same as v6, but maybe I'm just using it wrong 🤷‍♂️

### Actual behavior

`removeScriptTags` doesn't have any impact on the output file like it does in v6.

**Comment by ChristianMurphy** [comment]
Unified currently is designed to work with vfile 4 https://github.com/unifiedjs/unified/blob/115898a6bea4485a160864cdb96aae69021e0559/package.json#L59
Specifically with `contents` (https://github.com/unifiedjs/unified/blob/0f3b92833fd910c21edef423ad5891af7f11a82e/index.js#L43-L49) which changed in `vFile` 5 https://github.com/vfile/vfile/releases/tag/5.0.0
`to-vfile` 7 upgrades to `vFile` 5 https://github.com/vfile/to-vfile/releases/tag/7.0.0 and it not yet compatible with unified.

It will be supported in the next major version of unified https://github.com/unifiedjs/unified/issues/121
