### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by luxzeitlos** [vfile/to-vfile#19]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.0

### Steps to reproduce

have
```
import { read } from 'to-vfile';
```

### Expected behavior

it should import the `read` method as documented [here](https://github.com/vfile/to-vfile#api)

### Actual behavior

it can not import `read` because it is not [exported here](https://github.com/vfile/to-vfile/blob/main/index.js).

### Runtime

Node v14

### Package manager

npm v7

### OS

Linux

**Comment by wooorm** [comment]
I added [them recently](https://github.com/vfile/to-vfile/commit/1e417be0a1f47d2dba8f5a725b2a63cf27f27dde) but forgot to re-export them from `index.js`.

Would you be interested in working on a PR?

**Comment by gorango** [comment]
This still appears to be an issue:

```
npm i to-vfile
```
```
cat node_modules/to-vfile/index.js
```
```js
/**
 * @typedef {import('./lib/index.js').Compatible} Compatible
 * @typedef {import('./lib/index.js').Callback} Callback
 * @typedef {import('./lib/index.js').BufferEncoding} BufferEncoding
 * @typedef {import('./lib/index.js').Mode} Mode
 * @typedef {import('./lib/index.js').ReadOptions} ReadOptions
 * @typedef {import('./lib/index.js').WriteOptions} WriteOptions
 */

export {toVFile} from './lib/index.js'
```
```
cat package.json
```
```json
{
  "dependencies": {
    "to-vfile": "^7.2.0",
  }
}

```

**Comment by wooorm** [comment]
It looks like you’re getting 7.2.0 instead of 7.2.1?

**Comment by ChristianMurphy** [comment]
7.2.1 doesn't appear to be published yet 🤔 
https://unpkg.com/browse/to-vfile@7.2.1/

**Comment by wooorm** [comment]
😅 done!
