### ISSUE TITLE
Support promises

### ISSUE THREAD

**Issue by kachkaev** [vfile/to-vfile#4]
Glad to discover another awesome package from you @wooorm!

I'm experimenting with `vfile` in a Node.js environment that supports `async/await`. At the moment, reading `vfile` asynchronously looks like this:

```js
import * as toVfile from "to-vfile";
import { promisify } from "util";

const readVfile = promisify(toVfile.read);

(async () => {
  const f = await readVfile(path, 'utf-8');
  console.log(f);
})();
```

It'd be great if `read` and `write` methods returned promises out of box, just like `unified` does already! This would allow for just `const f = await toVfile.read(path, 'utf-8');`

**Comment by wooorm** [comment]
Sure, sounds like a plan! Are you able to work on a PR?

**Comment by kachkaev** [comment]
Will try not to forget next week :–)

**Comment by wooorm** [comment]
Sure! Take your time!

**Comment by wooorm** [comment]
Released in a minute, when Travis finishes!
