### ISSUE TITLE
Honor vfile.cwd when reading from disk

### ISSUE THREAD

**Issue by danburzo** [vfile/to-vfile#6]
Not sure if this is the right repo for it, or whether I should open it in [vfile/vfile](https://github.com/vfile/vfile), but currently I'm struggling with the following situation. I have this folder structure

```
my-project/
    - content/
        - post-1.md
        - post-2.md
```

with a script running in the root folder (`my-project`), I want to read the Markdown files relatively to the `content` folder (such that `content` does not appear in `vfile.path`). However, this does not work:

```js
vfile.read({
  path: '1.md',
  cwd: path.join(process.cwd(), 'content')
}, 'utf8')
```

is it fair to assume that when specifying a `cwd` for the vfile, that should be taken into consideration when performing `fs.read() / readSync()`? Right now, it seems to be ignored. 

If there are no implications I'm not aware of, I can submit a PR for this.

**Comment by wooorm** [comment]
Yes! I think it is!

**Comment by danburzo** [comment]
I've made the PR request, let me know if it looks okay!
