### ISSUE TITLE
Expose the VFile sup-dependency

### ISSUE THREAD

**Issue by zipang** [vfile/to-vfile#8]
I have a project where i use 3 packages of the vfile (excellent) family : `vfile`, `to-file` and `vfile-find-down`
It results in this tree of dependencies : 

```sh
19:54 $ tree node_modules/ | grep vfile
├── to-vfile
│   │   └── vfile
├── vfile
├── vfile-find-down
│   │   ├── to-vfile
│   │   └── vfile
```

So : the packages are duplicated, and that prevent me to have a single source of truth, for example when i want to upgrade the VFile prototype.
And worse : It's really easy to have one of these packages out of date with the latest releases, and the work of keeping with these releases up to date is duplicated between me and the vfile project !

**Comment by wooorm** [comment]
Weird, this shouldn’t happen for to-vfile. You should be able to remove the node modules, and `npm install` again, that should remove `vfile` in `to-vfile`.

> And worse : It's really easy to have one of these packages out of date with the latest releases, and the work of keeping with these releases up to date is duplicated between me and the vfile project !

`to-vfile` is already almost the same as `vfile`. Except the fact that passing a `string` as `options` is seen as `{path: options}` instead of `{contents: options}`. Do you really need `vfile` directly?

This is also how semver works 🤷‍♂️ You need to update stuff, but on the other hand there’s no breaking changes.

And finally: why update the prototype? Updating prototypes can generally cause bugs.

**Comment by zipang** [comment]
Hi Titus, thxx for your answer and all the awesome work !! :smiley: 👍 

> Weird, this shouldn’t happen for to-vfile. You should be able to remove the node modules, and npm install again, that should remove vfile in to-vfile.

So.. i reissued a `yarn install` on my project's root here is my tree after that : 
```sh
08:02 $ tree node_modules/ | grep vfile
├── to-vfile
├── vfile
├── vfile-find-down
│   │   └── to-vfile
```
So.. yep.. slightly better. Surely it occured in my dev because of the order the dependencies were added in the first place.
Still don't get it about why and how, is it a `yarn` or `npm` issue, do i have to issue other weird commands.... 

> And finally: why update the prototype? Updating prototypes can generally cause bugs. 

Really.. the point was not to debate about this controversial topic... :) But just to show what kind of weird behaviour duplicated packages can bring..

So.. finally : what would be your point _against_ exposing `VFile` inside `to_vfile` (and.. this goes to `vfile-find-down` exposing `VFile` and `toVFile`..)

It would allow package users to declare a _single dependency_ in their project :clap:, to enhance VFile prototype _if they want_ (and at their own risk), and be sure that every `vfile` instance is born equal without a doubt.
Maybe there are some downsides that i can't see right now.. :anguished:

**Comment by wooorm** [comment]
Sorry, but I don’t believe this makes sense. This goes against semver and wild tie your butt somewhere in the future. I’m not adding that to this project!

You shouldn’t need to use both `to-vfile` and `vfile`. And if you do, you can update them in the same go (I work on timely updates to both too). If `vfile` is updated but another project (e.g., `to-vfile`), you should create an issue or send a PR!

Anyway, package deduping from Yarn and npm should fix most of the other cases!
